### ISSUE TITLE
Vagrant Status: Error after pointing to config

### ISSUE THREAD

**Issue by ApeWare** [Bartzy/alfred-vagrant#1]
Installed fine. Ran configure and pointed to my vagrant file
![image](https://cloud.githubusercontent.com/assets/389759/18795310/ec6081cc-8191-11e6-8457-f3d1f9b450bd.png)

Next time I type `vg` It says "Vagrant Status: Error 
![image](https://cloud.githubusercontent.com/assets/389759/18795317/f58cf208-8191-11e6-8635-b71b398db3a7.png)

Not sure what the issue is. Suggestions?

**Comment by bartzy** [comment]
Hi,

Can you please provide the following:
1. Go to the folder with your Vagrantfile in it, and run (in terminal): `vagrant status --machine-readable` and paste the output.
2. Go to the Alfred Workflow Debugger (Instructions here: https://www.alfredapp.com/help/workflows/advanced/debugger/), change the "Log" option to "All Information" and then type `vg` into Alfred?
3. What is your Alfred version, Vagrant version and Virtualbox version?

Thanks.

**Comment by ApeWare** [comment]
# 1

``` bash
1474653187,default,metadata,provider,virtualbox
1474653187,default,provider-name,virtualbox
1474653187,default,state,running
1474653187,default,state-human-short,running
1474653187,default,state-human-long,The VM is running. To stop this VM%!(VAGRANT_COMMA) you can run `vagrant halt` to\nshut it down forcefully%!(VAGRANT_COMMA) or you can run `vagrant suspend` to simply\nsuspend the virtual machine. In either case%!(VAGRANT_COMMA) to restart it again%!(VAGRANT_COMMA)\nsimply run `vagrant up`.
1474653187,,ui,info,Current machine states:\n\ndefault                   running (virtualbox)\n\nThe VM is running. To stop this VM%!(VAGRANT_COMMA) you can run `vagrant halt` to\nshut it down forcefully%!(VAGRANT_COMMA) or you can run `vagrant suspend` to simply\nsuspend the virtual machine. In either case%!(VAGRANT_COMMA) to restart it again%!(VAGRANT_COMMA)\nsimply run `vagrant up`.
```

# 2

I started debugger, tried to **Configure Vagrant**, then typed *_vg_ in alfred again; here is the output

``` xml
Starting debug for 'Vagrant'

[2016-09-23 13:55:48][input.scriptfilter] <?xml version="1.0"?>
<items>
  <item valid="no">
    <title>Vagrant Status: Error</title>
    <subtitle>An error occured. Did you run 'vg configure' correctly?</subtitle>
    <icon>icons/error.png</icon>
  </item>
</items>
[2016-09-23 13:55:59][input.filefilter] Processing output of 'action.script' with arg '/Users/anash/Homestead/Vagrantfile'
[2016-09-23 13:56:14][input.scriptfilter] <?xml version="1.0"?>
<items>
  <item valid="no">
    <title>Vagrant Status: Error</title>
    <subtitle>An error occured. Did you run 'vg configure' correctly?</subtitle>
    <icon>icons/error.png</icon>
  </item>
</items>
```

# 3

**Alfred Version:** 3.1.1[737]
**Vagrant:** 1.8.1
**Virtual Box Version:** 5.0.20 r106931 - _there is an update available I can try 5.0.26_

**Comment by ApeWare** [comment]
FYI: I went ahead and updated VirtualBox to 5.0.26 r108824 and it didn't correct the issue.

**Comment by bartzy** [comment]
Thank you.

If you right-click on the Workflow in the Workflow list, then Open in Finder/Terminal - Is there a `vagrant_path` file there? What is its content?

**Comment by ApeWare** [comment]
Yes there is and it contains this path `/Users/anash/Homestead`, which is correct.

When I manually `vagrant up`, I do so from `~/Homestead`.

**Comment by bartzy** [comment]
I updated the workflow. Can you please try to remove it, [redownload](https://raw.github.com/Bartzy/alfred-vagrant/master/vagrant.alfredworkflow) it and try again?

**Comment by ApeWare** [comment]
**BOOM!** Fixed connection issue! Thanks for the quick fix. I'm an alfred fan and this seems like it will be a handy workflow.
- Tested start and stop; worked as expected.
- Tested SSH to vagrant and it gets stuck on password entry; will not accept input. I can open a new issue for this if you like.

![image](https://cloud.githubusercontent.com/assets/389759/18797032/e5466e4e-8199-11e6-8311-9424a4f6f7e3.png)

**Comment by bartzy** [comment]
Great.

Are you sure it isn't accepting input? It doesn't show the input for password in most terminals (Not related to this workflow).
Do you use a password for SSH or a certificate (for this vagrant instance)?

**Comment by ApeWare** [comment]
You are correct it is actually accepting input but I connect using a cert so I don't need to enter a password. To be clear this is requiring a password when I shouldn't need one.

My process, before this, is:
- `cd ~/Homestead`
- `vagrant up`
- `vm` which is just an alias to `vagrant ssh`

Consider this a potential idea for improvement, but not a deal breaker:
- vagrant ssh using cert
- iTerm support

Great job so far and, even for the quick access to vagrant up/suspend/status, it will be valuable. Thanks for taking the time.

**Comment by bartzy** [comment]
You're welcome!

Actually, you can make iTerm work - Go to the Workflow itself in Alfred, locate the `ssh:` Open URL action, and change the `Browser` to iTerm. It should work (I use it :)).

![image 2016-09-23 at 21 42 53](https://cloud.githubusercontent.com/assets/167339/18797549/13440de6-81d7-11e6-8976-43ad17343bce.png)

Regarding the cert - I use a cert and it works as well. Do you use the default `~/.ssh/id_rsa` path for your certificate?

**Comment by ApeWare** [comment]
Made workflow change to iTerm, Nice! Now it uses iTerm.
Yes, I do use the default path.

**Comment by bartzy** [comment]
So I don't quite know why it doesn't pick up your certificate. It just basically does `ssh -p2222 root@localhost`. If that works for you from an open iTerm tab, then it's weird that it asks for a password with the `vg ssh` keyword.

**Comment by ApeWare** [comment]
OK, I have it sorted out. I use Homestead (a prepared box for Laravel development) and it uses `vagrant@`, not `root@`, to ssh. I made that change in the workflow and it is working fine now; using my cert.

Thanks for the quick assistance!

**Comment by bartzy** [comment]
Ah, got it. 

No problem!
